---
- name: Downloading cfssl binaries
  ansible.builtin.get_url:
    url: "{{ cfssl_bin_download_url }}"
    dest: "{{ cfssl_bin_directory }}/{{ item }}"
    mode: 0755
    owner: "{{ cfssl_owner }}"
    group: "{{ cfssl_group }}"
    checksum: "sha256:{{ cfssl_checksum_url }}"
  with_items:
    - cfssl
    - cfssl-bundle
    - cfssl-certinfo
    - cfssl-newkey
    - cfssl-scan
    - cfssljson
    - mkbundle
    - multirootca
  tags:
    - cfssl
